// <auto-generated />
using System;
using Demothidecu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demothidecu.Migrations
{
    [DbContext(typeof(csdl_dienkeContext))]
    [Migration("20250227150721_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Demothidecu.Models.Dienke", b =>
                {
                    b.Property<string>("Madk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("madk");

                    b.Property<string>("Makh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("makh");

                    b.Property<DateTime?>("Ngaydk")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaydk");

                    b.HasKey("Madk");

                    b.HasIndex("Makh");

                    b.ToTable("dienke", (string)null);
                });

            modelBuilder.Entity("Demothidecu.Models.Khachhang", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("makh");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dienthoai");

                    b.Property<string>("Tenkh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenkh");

                    b.HasKey("Makh");

                    b.ToTable("khachhang", (string)null);
                });

            modelBuilder.Entity("Demothidecu.Models.Kysudung", b =>
                {
                    b.Property<string>("Maky")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("maky");

                    b.Property<DateTime?>("Denngay")
                        .HasColumnType("datetime")
                        .HasColumnName("denngay");

                    b.Property<DateTime?>("Tungay")
                        .HasColumnType("datetime")
                        .HasColumnName("tungay");

                    b.HasKey("Maky");

                    b.ToTable("kysudung", (string)null);
                });

            modelBuilder.Entity("Demothidecu.Models.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("manv");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dienthoai");

                    b.Property<string>("Tennv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tennv");

                    b.HasKey("Manv");

                    b.ToTable("nhanvien", (string)null);
                });

            modelBuilder.Entity("Demothidecu.Models.Sudungdien", b =>
                {
                    b.Property<string>("Maky")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("maky");

                    b.Property<string>("Madk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("madk");

                    b.Property<int?>("Chisocu")
                        .HasColumnType("int")
                        .HasColumnName("chisocu");

                    b.Property<int?>("Chisomoi")
                        .HasColumnType("int")
                        .HasColumnName("chisomoi");

                    b.Property<string>("Manv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("manv");

                    b.HasKey("Maky", "Madk");

                    b.HasIndex("Madk");

                    b.HasIndex("Manv");

                    b.ToTable("sudungdien", (string)null);
                });

            modelBuilder.Entity("Demothidecu.Models.Dienke", b =>
                {
                    b.HasOne("Demothidecu.Models.Khachhang", "MakhNavigation")
                        .WithMany("Dienkes")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK_dienke_khachhang");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("Demothidecu.Models.Sudungdien", b =>
                {
                    b.HasOne("Demothidecu.Models.Dienke", "MadkNavigation")
                        .WithMany("Sudungdiens")
                        .HasForeignKey("Madk")
                        .IsRequired()
                        .HasConstraintName("FK_sudungdien_dienke");

                    b.HasOne("Demothidecu.Models.Kysudung", "MakyNavigation")
                        .WithMany("Sudungdiens")
                        .HasForeignKey("Maky")
                        .IsRequired()
                        .HasConstraintName("FK_sudungdien_kysudung");

                    b.HasOne("Demothidecu.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Sudungdiens")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_sudungdien_nhanvien");

                    b.Navigation("MadkNavigation");

                    b.Navigation("MakyNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Demothidecu.Models.Dienke", b =>
                {
                    b.Navigation("Sudungdiens");
                });

            modelBuilder.Entity("Demothidecu.Models.Khachhang", b =>
                {
                    b.Navigation("Dienkes");
                });

            modelBuilder.Entity("Demothidecu.Models.Kysudung", b =>
                {
                    b.Navigation("Sudungdiens");
                });

            modelBuilder.Entity("Demothidecu.Models.Nhanvien", b =>
                {
                    b.Navigation("Sudungdiens");
                });
#pragma warning restore 612, 618
        }
    }
}
